Replace bower rails for webpacker
MarsBased/pathfinder-rails pull request #78
Opened 2018-02-02 12:27 UTC by dvdgs88

Closes #25

2018-02-02 18:21 UTC, pablorc requested changes
Small fixes requested.

2018-02-02 18:21 UTC, pablorc commented on pathfinder.rb
> +     add_recipe(Recipes::ActiveAdmin.new(´self))
A wild ´ appeared!

2018-02-02 18:21 UTC, pablorc commented on recipes/webpacker.rb
> +      @template.run "yarn add #{package_command_resources}"
I don't have yarn installed. Maybe we should install it before in the script, or document it at the README?

2018-05-17 08:09 UTC, dvdgs88 commented
@pablorc I've added the official installation instructions link to the readme, as the installation is specific to the user OS.

2018-05-17 10:34 UTC, merged